version: '3'

services: 
  bind9:
    container_name: dns-demo-2
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=UTC
    ports: 
      - "192.168.50.222:53:53/tcp"
      - "192.168.50.222:53:53/udp"
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    restart: unless-stopped