fullnameOverride: prometheus

defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: false
    configReloaders: true
    general: false
    k8s: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: true
    kubeApiserverHistogram: true
    kubeApiserverSlos: true
    kubelet: false
    kubeProxy: false
    kubePrometheusGeneral: false
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeScheduler: false
    kubeStateMetrics: true
    network: true
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true
    prometheus: false

    prometheusOperator: false
alertmanager:
  enabled: true 
  alertmanagerSpec:
    externalURL: 'grafana.k3s.domain.com'
  config:
    global:
      slack_api_url: 'https://hooks.slack.com/services/T04RBAEHU//'  # Replace with your Slack webhook URL
    receivers:
      - name: 'slack-notifications'
        slack_configs:
          - channel: 'k3s-alertmanager'  # Replace with your Slack channel
            send_resolved: true
            title: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}'
            text: >-
              {{ range .Alerts }}
              *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
              *Description:* {{ .Annotations.description }}
              *Link:* <http://grafana.k3s.domain.com/alerting/list|View in Grafana>
              {{ end }}
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'slack-notifications'
      routes:
        - match:
            severity: critical
          receiver: 'slack-notifications'
  ingress:
    enabled: false


grafana:
  enabled: true
  fullnameOverride: grafana
  forceDeployDatasources: false
  forceDeployDashboards: false
  defaultDashboardsEnabled: true
  defaultDashboardsTimezone: utc
  serviceMonitor:
    enabled: true
  admin:
    existingSecret: grafana-admin-credentials
    userKey: admin-user
    passwordKey: admin-password
  service:
    type: LoadBalancer
    loadBalancerIP: "192.168.0.227"
  # ingress:
  #   enabled: true
  #   annotations:
  #     kubernetes.io/ingress.class: "traefik-external"
  #     cert-manager.io/cluster-issuer: "letsencrypt-staging"
  #   hosts:
  #     - grafana.domain.com
  #   paths:
  #     - /
  #   tls:
  #     - hosts:
  #         - grafana.domain.com
  #       secretName: grafana-com-tls


kubeApiServer:
  enabled: true

kubelet:
  enabled: true
  serviceMonitor:
    metricRelabelings:
      - action: replace
        sourceLabels:
          - node
        targetLabel: instance

kubeControllerManager:
  enabled: false
  endpoints: # ips of servers 
    - 192.168.0.22
    - 192.168.0.19
    - 192.168.0.82

coreDns:
  enabled: true

kubeDns:
  enabled: false

kubeEtcd:
  enabled: false
  endpoints: # ips of servers
    - 192.168.0.22
    - 192.168.0.19
    - 192.168.0.82
  service:
    enabled: true
    port: 2381
    targetPort: 2381

kubeScheduler:
  enabled: false
  endpoints: # ips of servers
    - 192.168.0.22
    - 192.168.0.19
    - 192.168.0.82

kubeProxy:
  enabled: false
  endpoints: # ips of servers
    - 192.168.0.22
    - 192.168.0.19
    - 192.168.0.82

kubeStateMetrics:
  enabled: true

kube-state-metrics:
  fullnameOverride: kube-state-metrics
  selfMonitor:
    enabled: true
  prometheus:
    monitor:
      enabled: true
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: kubernetes_node

nodeExporter:
  enabled: true
  serviceMonitor:
    relabelings:
      - action: replace
        regex: (.*)
        replacement: $1
        sourceLabels:
          - __meta_kubernetes_pod_node_name
        targetLabel: kubernetes_node

prometheus-node-exporter:
  fullnameOverride: node-exporter
  podLabels:
    jobLabel: node-exporter
  extraArgs:
    - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
    - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
  service:
    portName: http-metrics
  prometheus:
    monitor:
      enabled: true
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: kubernetes_node
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 2048Mi

prometheusOperator:
  enabled: false
  prometheusConfigReloader:
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1"

prometheus:
  enabled: true
  prometheusSpec:
    scrapeInterval: 30s
    evaluationInterval: 30s
    replicas: 3
    replicaExternalLabelName: "replica"
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    retention: 6h
    enableAdminAPI: true
    walCompression: true
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "4Gi"
        cpu: "2"

thanosRuler:
  enabled: false

