# Default values for runner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

github:
  repository: osherlevi7/dev #["oufinx/repo1", "oufinx/repo2"]
  # organization: 
  labels: [k8s]

namespace: actions-runner-system

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  scaleDownDelaySecondsAfterScaleOut: 300

# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: team
#           operator: In
#           values:
#           - engineers

tolerations: []

nodeSelector: {}
