apiVersion: v1
kind: PersistentVolume
metadata:
  name: allure-persistent-volume
  namespace: allure-docker-service
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  capacity:
    storage: 3Gi
  #Replace hostPath for storage cloud solution
  hostPath:
    path: /allure/projects
