{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gophish.fullname" . }}
  namespace: {{ include "gophish.namespaceName" . }}
  labels:
    {{- include "gophish.labels" . | nindent 4 }}
data:
  config.json: |
    {{- tpl .Values.config.file . | nindent 4 }}
{{- end }}