{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gophish.fullname" . }}
  namespace: {{ include "gophish.namespaceName" . }}
  labels:
    {{- include "gophish.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.deployment.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gophish.selectorLabels" . | nindent 6 }}
  template:
    {{- include "gophish.podTemplate" . | nindent 4 }}
{{- end }}
