on: [pull_request]

defaults:
  run:
    shell: bash

env:
  TARGET_BRANCH: ${{ github.base_ref }}

jobs:

  call-infracost-gke-dev:
    name:  GKE-DEV
    uses: ./.github/workflows/infracost.yaml
    with:
      terraform_env: gke/dev
    secrets: inherit

  call-infracost-gke-prod:
    name:  GKE-PROD
    uses: ./.github/workflows/infracost.yaml
    with:
      terraform_env: gke/prod
    secrets: inherit

  call-infracost-vertex-dev:
    name:  VERTEX-DEV
    uses: ./.github/workflows/infracost.yaml
    with:
      terraform_env: vertex-ai/dev
    secrets: inherit

  call-infracost-vertex-prod:
    name:  VERTEX-PROD
    uses: ./.github/workflows/infracost.yaml
    with:
      terraform_env: vertex-ai/prod
    secrets: inherit
